### ISSUE TITLE
OAuth2.0的身份验证

### ISSUE THREAD

**Issue by LeadroyaL** [sgjsakura/CC98vNext#9]
1、使用API中Get Me来获取当前用户的信息；
2、额，还有什么要做的嘛？

主要是我不清楚我要实现什么功能，请樱桃指点一下流程。。。Orz

**Comment by sgjsakura** [comment]
@LeadroyaL 目前的最基本要求就是能够实现登录，在登录之后主页上显示用户名~

**Comment by LeadroyaL** [comment]
@sgjsakura 好~~使用的开发者key是用哪个呢？在解密的最后一个页面里的哪个？
该key如何防止被用户看到？

**Comment by sgjsakura** [comment]
@LeadroyaL 自己申请一个ID吧，ID所有人都能看到，但是Secret看不到就好啦

**Comment by LeadroyaL** [comment]
@sgjsakura Secret这个值有什么用吗？好像没有用到诶。。。

**Comment by LeadroyaL** [comment]
@sgjsakura 经过一天的努力，现在通过修改URL和请求头的方法，可以拿到token了，也可以通过该Request Head来拿到userName，URL重定向也测试过了，但是问题是：1、我该如何将拿到的userName显示到界面上？2、C#架构的东西我从来没有写过，我该如何用C#来重定向，以及我拿到UserName是在界面加载之前还是在数码时候？

**Comment by sgjsakura** [comment]
@LeadroyaL 先做了一个临时版本以提升项目进度，请继续加油~
